export { default as Header } from "./Header";
export { default as Footer } from "./Footer";
export { default as Sidebar } from "./Sidebar";
export { default as Modal } from "./Modal";
export { default as Banner } from "./home-layouts/Banner";
export { default as About } from "./home-layouts/About";
export { default as Category } from "./home-layouts/Category";
export { default as Team } from "./home-layouts/Team";
export { default as Faqs } from "./home-layouts/Faqs";
export { default as Blog } from "./home-layouts/Blog";
export { default as Accordian } from "./home-layouts/Accordian";
export { default as Features } from "./home-layouts/Features";
export { default as SocialMediaIcons } from "./SocialMediaIcons"
